project 'SwpShareViewDemo.xcodeproj'

# Uncomment this line to define a global platform for your project

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'SwpShareViewDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SwpShareViewDemo
  
    pod 'pop'
    
    pod 'SwpShareView', :path => '../'

end
